/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multicorn_opensurf_Opensurf */

#ifndef _Included_com_multicorn_opensurf_Opensurf
#define _Included_com_multicorn_opensurf_Opensurf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multicorn_opensurf_Opensurf
 * Method:    surflib_surfDet
 * Signature: (JJIIIF)V
 */
JNIEXPORT void JNICALL Java_com_multicorn_opensurf_Opensurf_surflib_1surfDet
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jfloat);

/*
 * Class:     com_multicorn_opensurf_Opensurf
 * Method:    surflib_surfDes
 * Signature: (JJJZ)V
 */
JNIEXPORT void JNICALL Java_com_multicorn_opensurf_Opensurf_surflib_1surfDes
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif


void Mat_to_vector_KeyPoint(cv::Mat&, std::vector<cv::KeyPoint>&);

void vector_KeyPoint_to_Mat(std::vector<cv::KeyPoint>&, cv::Mat&);
